### PR TITLE
Sync of Master Branch of Fork

### PR DESCRIPTION
**Pull request by animeshsrivastava24**
syncing the master branch of my fork from the parent repository

### CODE REVIEW

**Comment by animeshsrivastava24** [comment]
@per1234 I was carrying out this to sync the fork https://github.com/arduino/reference-hi/pull/7#issuecomment-502973571
Please guide.

**Comment by per1234** [comment]
I'm glad you're working with Git command line now and that I was able to be of some assistance in that process. Please let me know if you have any questions about that. There is a fairly steep learning curve to Git, but luckily the GitHub web interface gives a nice introduction to the basics in a friendly format. However, once you start to need to do anything beyond the basics, the GitHub web interface becomes extremely limiting.

If you prefer using a GUI instead of the command line, you might look at the various Git client applications that are available.

After getting started with the GitHub web interface, I moved on to [GitHub Desktop](https://desktop.github.com/). At that time, GitHub Desktop was very easy to use, with a very simple and easy to use interface. I know a lot of changes have been made to GitHub Desktop in the years since I used it last so I can't say whether it's still any good (or maybe even better).

After a while, I found that I was constantly using Git from the command line for things that GitHub Desktop didn't support so I went looking for a better Git client. I tried all the Windows compatible Git clients and was very disappointed in most of them when compared to GitHub Desktop. The extremely popular ones like GitKraken and Sourcetree seem to be focused mainly on looking "beautiful". Software is not a fashion statement for me. I want functionality and could care less how it looks. Finally I discovered [Git Extensions](https://github.com/gitextensions/gitextensions), which was by far the best of all options at that time. Unfortunately, it recently changed to being for Windows only (though not necessarily permanently). There are still some things that are only possible, or just more efficient to do, from the command line, but Git Extensions' GUI provides all the functionality I could want.

The path of GitHub web interface > GitHub Desktop > Git Extensions worked very well for me because it provided a nice learning curve. Git Extensions would probably be intimidating to someone coming directly from the GitHub web interface. Assuming GitHub Desktop still provides a simplified, beginner friendly interface, I would recommend it to someone who is relatively new to Git.

**Comment by animeshsrivastava24** [comment]
Thank you so much for the guidance, I used to work with the git command line when I was introduced to version control but due to lack of proper guidance and having less knowledge of open source interaction I switched to Desktop Interface and didn't explore much in-depth the potential of command line, but the recent events have again developed a sense of excitement in me related to command line and it's vast potential, all thanks to you.
> I'm glad you're working with Git command line now and that I was able to be of some assistance in that process. Please let me know if you have any questions about that. There is a fairly steep learning curve to Git, but luckily the GitHub web interface gives a nice introduction to the basics in a friendly format. However, once you start to need to do anything beyond the basics, the GitHub web interface becomes extremely limiting.


> After getting started with the GitHub web interface, I moved on to [GitHub Desktop](https://desktop.github.com/). At that time, GitHub Desktop was very easy to use, with a very simple and easy to use interface. I know a lot of changes have been made to GitHub Desktop in the years since I used it last so I can't say whether it's still any good (or maybe even better).
> 
> After a while, I found that I was constantly using Git from the command line for things that GitHub Desktop didn't support so I went looking for a better Git client. I tried all the Windows compatible Git clients and was very disappointed in most of them when compared to GitHub Desktop. The extremely popular ones like GitKraken and Sourcetree seem to be focused mainly on looking "beautiful". Software is not a fashion statement for me. I want functionality and could care less how it looks. Finally I discovered [Git Extensions](https://github.com/gitextensions/gitextensions), which was by far the best of all options at that time. Unfortunately, it recently changed to being for Windows only (though not necessarily permanently). There are still some things that are only possible, or just more efficient to do, from the command line, but Git Extensions' GUI provides all the functionality I could want.
> 

Sure, I'll explore Git Extensions and try to use their potential to my work.
> The path of GitHub web interface > GitHub Desktop > Git Extensions worked very well for me because it provided a nice learning curve. Git Extensions would probably be intimidating to someone coming directly from the GitHub web interface. Assuming GitHub Desktop still provides a simplified, beginner friendly interface, I would recommend it to someone who is relatively new to Git.


Also, yesterday during the process of sync, I tried new software and found it useful [Sublime Merge](https://www.sublimemerge.com/), even though I wasn't able to explore much in it and used Sublime Editor and git command line to remove my conflicts.

Also @per1234 , I have a small request if you can review and help me with feedback on my work for Arduino Core (Here: https://github.com/animeshsrivastava24/Arduino-Core-Documentation).
I have submitted my Season of Doc Proposal and wanted to inform you about my display name, I thought  it's important because I never used/associated it with my Github Account
Display Name : **thickblackmark45** 
The display name is the first part of my email address thickblackmark45@gmail.com (used for season-of-docs interaction)

**Comment by per1234** [comment]
>I have a small request if you can review and help me with feedback on my work for Arduino Core

Since the "Technical writer exploration" phase of Season of Docs has already ended (as of May 29), I am no longer permitted to assist with your project proposal. If your application for the Arduino cores documentation project is accepted then your mentor (which might be me) would certainly provide plenty of review and feedback at the appropriate phase of the program.

>and wanted to inform you about my display name, I thought it's important because I never used/associated it with my Github Account

Noted. Thanks!

**Pull request closed without merging**
